# Generated by Django 5.2.4 on 2025-07-24 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='uploads/conversion/')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='results/conversion/')),
                ('conversion_type', models.CharField(choices=[('pdf2docx', 'PDF to Word'), ('pdf2pptx', 'PDF to PowerPoint'), ('pdf2xlsx', 'PDF to Excel'), ('pdf2jpg', 'PDF to JPG'), ('pdf2png', 'PDF to PNG'), ('pdf2txt', 'PDF to TXT'), ('pdf2html', 'PDF to HTML'), ('docx2pdf', 'Word to PDF'), ('pptx2pdf', 'PowerPoint to PDF'), ('xlsx2pdf', 'Excel to PDF'), ('jpg2pdf', 'JPG to PDF'), ('png2pdf', 'PNG to PDF'), ('txt2pdf', 'TXT to PDF'), ('html2pdf', 'HTML to PDF'), ('merge', 'Merge PDF'), ('split', 'Split PDF'), ('compress', 'Compress PDF'), ('rotate', 'Rotate PDF'), ('edit', 'Edit PDF'), ('sign', 'Sign PDF'), ('esign', 'Convert PDF to eSign'), ('pdf2cad', 'PDF to CAD'), ('ocr', 'OCR PDF'), ('protect', 'Protect PDF'), ('unlock', 'Unlock PDF')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
