# Generated by Django 5.2.4 on 2025-07-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('internet', 'Internet'), ('printing', 'Printing'), ('government', 'Government'), ('financial', 'Financial'), ('education', 'Education'), ('business', 'Business'), ('tech', 'Tech Services'), ('travel', 'Travel'), ('entertainment', 'Entertainment')], max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
